"""Initial migration with simplified session model

Revision ID: b6a32e341acd
Revises: 
Create Date: 2025-08-03 20:34:54.067685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a32e341acd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_tags')
    op.drop_index('ix_session_id', table_name='session')
    op.drop_table('session')
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'session', ['session_id'], ['id'])
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('session_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_created_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='session_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='session_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_session_id', 'session', ['id'], unique=False)
    op.create_table('session_tags',
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name='session_tags_session_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='session_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('session_id', 'tag_id', name='session_tags_pkey')
    )
    # ### end Alembic commands ###
