"""Update session table: remove name, add user_created_id

Revision ID: d443e7419559
Revises: 0bb3fe6f2e6b
Create Date: 2025-08-03 18:34:28.114608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd443e7419559'
down_revision: Union[str, None] = '0bb3fe6f2e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, clean up existing data - delete orphaned messages without sessions
    op.execute('DELETE FROM chat_messages WHERE session_id IS NULL')
    
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    
    # Same cleanup for prompts
    op.execute('DELETE FROM prompt_check WHERE project_id IS NULL')
    op.alter_column('prompt_check', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('session', sa.Column('user_created_id', sa.String(), nullable=True))
    op.drop_column('session', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('session', 'user_created_id')
    op.alter_column('prompt_check', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=True)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
